Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ABARROTES_CORE.Models
{
    public class ApplicationDbContext:DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options):base(options)
        {

        }
        public DbSet<Product> Product { get; set; }
    }
}

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Models/ErrorViewModel.cs
using System;

namespace ABARROTES_CORE.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ABARROTES_CORE.Models
{
    public class Product
    {
        [Key]
        [Display(Name = "ID")]
        public int Prodid { get; set; }

        [Required(ErrorMessage = "Introduce nombre del producto")]
        [Display(Name = "Producto")]
        public String Prodname { get; set; }

        [Required(ErrorMessage = "Introduce el departamento")]
        [Display(Name = "Departamento")]
        public String Depar { get; set; }

        [Required(ErrorMessage = "Introduce el precio del producto")]
        [Display(Name = "Precio")]
        [Range(1, 1000)]
        public int Price { get; set; }

        [Display(Name = "Descuento disponible ")]
        public String Disc { get; set; }

    }
}

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Controllers/MyProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ABARROTES_CORE.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ABARROTES_CORE.Controllers
{
    public class MyProductController : Controller
    {  
        private readonly ApplicationDbContext db;
        public MyProductController (ApplicationDbContext d_b)
        {
            db = d_b;
        }

        // GET: MyProductController
        public ActionResult Index()
        {
            var displaydata = db.Product.ToList();
            return View(displaydata);
        }
        [HttpGet]
        public async Task<IActionResult> Index(string ProdSearch)
        {
            ViewData["GetProduct"] = ProdSearch;
            var prquery = from x in db.Product select x;
            if (!String.IsNullOrEmpty(ProdSearch))
            {
                prquery = prquery.Where(x => x.Prodname.Contains(ProdSearch));
            }
            return View(await prquery.AsNoTracking().ToListAsync());
        }
        // GET: MyProductController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if(id==null)
            {
                return RedirectToAction("Index");
            }
            var getProdDetail = await db.Product.FindAsync(id);
            return View(getProdDetail);
        }
        
        // GET: MyProductController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MyProductController/Create
        [HttpPost]
        public async Task<IActionResult> Create(Product newPr)
        {
            if(ModelState.IsValid)
            {
                db.Add(newPr);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(newPr);
           
        }

        // GET: MyProductController/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getProdDetail = await db.Product.FindAsync(id);
            return View(getProdDetail);
        }

        // POST: MyProductController/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(Product oldP)
        {
            if (ModelState.IsValid)
            {
                db.Update(oldP);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldP);
        }

        // GET: MyProductController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getProdDetail = await db.Product.FindAsync(id);
            return View(getProdDetail);
        }

        // POST: MyProductController/Delete/5
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {

            var getProdDetail = await db.Product.FindAsync(id);
            db.Product.Remove(getProdDetail);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");

        }
    }
}

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Views/MyProduct/Create.cshtml
@model ABARROTES_CORE.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Prodname" class="control-label"></label>
                <input asp-for="Prodname" class="form-control" />
                <span asp-validation-for="Prodname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Depar" class="control-label"></label>
                <input asp-for="Depar" class="form-control" />
                <span asp-validation-for="Depar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Disc" class="control-label"></label>
                <input asp-for="Disc" class="form-control" />
                <span asp-validation-for="Disc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Views/MyProduct/Delete.cshtml
@model ABARROTES_CORE.Models.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>¿Desea eliminar este producto?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prodid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prodid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prodname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prodname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Depar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Depar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disc)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a la lista</a>
    </form>
</div>

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Views/MyProduct/Details.cshtml
@model ABARROTES_CORE.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prodid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prodid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prodname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prodname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Depar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Depar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disc)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Prodid }) |
    <a asp-action="Index">Regresar a la lista</a>
</div>

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Views/MyProduct/Edit.cshtml
@model ABARROTES_CORE.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Prodid" class="control-label"></label>
                <input asp-for="Prodid" class="form-control" readonly />
                <span asp-validation-for="Prodid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prodname" class="control-label"></label>
                <input asp-for="Prodname" class="form-control" />
                <span asp-validation-for="Prodname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Depar" class="control-label"></label>
                <input asp-for="Depar" class="form-control" />
                <span asp-validation-for="Depar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Disc" class="control-label"></label>
                <input asp-for="Disc" class="form-control" />
                <span asp-validation-for="Disc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Views/MyProduct/Index.cshtml
@model IEnumerable<ABARROTES_CORE.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Catálogo de Productos</h1>

<p>
    <a asp-action="Create">Añadir Producto</a>
</p>
<form asp-action="Index" method="get">
    <p>
        <input type="search" placeholder="Ingresa Nombre del Producto" name="ClieSearch"
               value="@ViewData["GetProduct"]" style="width:400px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver todos</a>
    </p>
</form>
<table class="table" BackColor="LightBlue">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Prodid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prodname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Prodid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prodname)
            </td>
            <td>
                <h6>$@Html.DisplayFor(modelItem => item.Price)</h6>
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Prodid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Details", "Details", new { id = item.Prodid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Prodid }, new { @class = "btn btn-success" })
            </td>
        </tr>
}
    </tbody>
</table>

Examen 3ra Semana (CRUD MVC)/ABARROTES_CORE/ABARROTES_CORE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ABARROTES_CORE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="MyProduct" asp-action="Index">ABARROTES_CORE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyProduct" asp-action="Index">Home</a>
                        </li>
                  
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ABARROTES_CORE - <a asp-area="" asp-controller="MyProduct" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>